name: graphical_programming
version: 0.0.1
description: Program Model
author: Yuki Suga <ysuga@ysuga.net>
homepage: http://ysuga.net
documentation: http://docs.newtify.com
dependencies :
  connection_model : 
    path : ../connection_model.dart
  program_model : 
    path : ../program_model.dart
  connection_program_converter:
    path : ../connection_program_converter.dart
  stagexl : 0.12.0
  browser : 0.10.0

dev_dependencies : {}